added footer
miculnapoleon/personal-website pull request #1
Opened 2022-07-25 20:49 UTC by miculnapoleon

2022-07-25 20:56 UTC, MercurA requested changes

2022-07-25 20:56 UTC, MercurA commented on components/footer/Footer.jsx
> +    icon: <a href="https://www.behance.net//" target="__blank" className={styles.linkB}> <Image key={2}  width={20} height={20} src="/images/behance.svg" /></a>,
link needs correction

2022-07-25 20:56 UTC, MercurA commented on components/footer/Footer.jsx
> +    icon: <a href="https://www.behance.net//" target="__blank" className={styles.linkB}> <Image key={2}  width={20} height={20} src="/images/behance.svg" /></a>,
also use `rel=”noopener noreferrer” ` for security resons

2022-07-25 20:56 UTC, MercurA commented on components/footer/footer.module.scss
> +    fill:yellowgreen; }
format

2022-07-27 19:47 UTC, miculnapoleon commented on components/footer/footer.module.scss
> +    fill:yellowgreen; }
fixed

2022-08-11 19:39 UTC, merged